### ISSUE TITLE
Improve Readme to say **where** you should add the .use(layouts())

### ISSUE THREAD

**Issue by MorganConrad** [totocaster/metalsmith-tags#47]
I know that wise Metalsmith users are suppossed to figure this stuff out, but it would have saved me half an hour if you said  "put `use(tags())` **after** `use(layouts()).`

**Comment by HaoZeke** [comment]
Actually I get errors after layouts...

```js
Error in plugin 'gulp-metalsmith'
Message:
    File.contents can only be a Buffer, a Stream, or null.
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
Stack:
Error: File.contents can only be a Buffer, a Stream, or null.
    at File.set (/home/haozeke/Github/Pandoc/grimoire/node_modules/gulp-util/node_modules/vinyl/index.js:148:13)
    at baseAssignValue (/home/haozeke/Github/Pandoc/grimoire/node_modules/lodash/lodash.js:2580:21)
    at assignValue (/home/haozeke/Github/Pandoc/grimoire/node_modules/lodash/lodash.js:2496:9)
    at copyObject (/home/haozeke/Github/Pandoc/grimoire/node_modules/lodash/lodash.js:4819:11)
    at /home/haozeke/Github/Pandoc/grimoire/node_modules/lodash/lodash.js:12653:7
    at Function.<anonymous> (/home/haozeke/Github/Pandoc/grimoire/node_modules/lodash/lodash.js:4892:13)
    at apply (/home/haozeke/Github/Pandoc/grimoire/node_modules/lodash/lodash.js:496:27)
    at Function.<anonymous> (/home/haozeke/Github/Pandoc/grimoire/node_modules/lodash/lodash.js:6600:16)
    at /home/haozeke/Github/Pandoc/grimoire/node_modules/gulp-metalsmith/lib/index.js:90:16
    at /home/haozeke/Github/Pandoc/grimoire/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/home/haozeke/Github/Pandoc/grimoire/node_modules/lodash/lodash.js:3001:24)
    at Function.forOwn (/home/haozeke/Github/Pandoc/grimoire/node_modules/lodash/lodash.js:13002:24)
    at pushToStream (/home/haozeke/Github/Pandoc/grimoire/node_modules/gulp-metalsmith/lib/index.js:87:7)
    at /home/haozeke/Github/Pandoc/grimoire/node_modules/gulp-metalsmith/lib/index.js:79:9
    at next (/home/haozeke/Github/Pandoc/grimoire/node_modules/ware/lib/index.js:82:27)
    at /home/haozeke/Github/Pandoc/grimoire/node_modules/wrap-fn/index.js:121:18
[05:30:06] 'default' errored after 2.03 s
```

**Comment by benpolinsky** [comment]
Yeah, I've moved my call to before layouts.

**Comment by HaoZeke** [comment]
It does need to be after **permalinks** though.
