### ISSUE TITLE
Error: Invalid result object from transform.

### ISSUE THREAD

**Issue by jcrawford** [totocaster/metalsmith-tags#56]
When I have the following in my `article.njk` template the build fails.

```
{% if tags %}
        <li class="posted-tags">
            {% for tag in tags %}
            <a href="{{ site.url }}/tags/{{ tag.slug }}/index.html">{{ tag.name | uppercase }}</a>
            {% endfor %}
        </li>
{% endif %}
```

The metadata is in place, any thoughts on why this is happening?

<img width="443" alt="screen shot 2019-01-03 at 4 22 06 pm" src="https://user-images.githubusercontent.com/875341/50663346-5f8b4b80-0f77-11e9-8f30-17f2565596dc.png">

```
  metalsmith-debug-ui writing data to build +692ms
Error: Invalid result object from transform.
    at normalize (/Users/Shared/Dropbox/Projects/jcrawford.maddius/node_modules/jstransformer/index.js:64:11)
    at tryCallOne (/Users/Shared/Dropbox/Projects/jcrawford.maddius/node_modules/promise/lib/core.js:37:12)
    at /Users/Shared/Dropbox/Projects/jcrawford.maddius/node_modules/promise/lib/core.js:123:15
    at flush (/Users/Shared/Dropbox/Projects/jcrawford.maddius/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
/Users/Shared/Dropbox/Projects/jcrawford.maddius/build.js:158
            throw err;
            ^

Error: Invalid result object from transform.
    at normalize (/Users/Shared/Dropbox/Projects/jcrawford.maddius/node_modules/jstransformer/index.js:64:11)
    at tryCallOne (/Users/Shared/Dropbox/Projects/jcrawford.maddius/node_modules/promise/lib/core.js:37:12)
    at /Users/Shared/Dropbox/Projects/jcrawford.maddius/node_modules/promise/lib/core.js:123:15
    at flush (/Users/Shared/Dropbox/Projects/jcrawford.maddius/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jcrawford.github.io@1.0.0 debug: `DEBUG=* node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jcrawford.github.io@1.0.0 debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jcrawford/.npm/_logs/2019-01-03T21_33_23_020Z-debug.log
```

I I change `tags` to anything else in the for loop then the error goes away but the tags are not displayed because they don't exist at that level, such as `post.tags` or `this.tags`.

**Comment by jcrawford** [comment]
Nunjucks didn't like | uppercase as it should have been | capitalize
